
username = "jouvash@gmail.com" # Here enter your API user name
password = "x9T5Kbs7MQj2k4A6L" # Here enter your API password
priaid_authservice_url = "https://sandbox-authservice.priaid.ch/login" # Be aware that sandbox link is for testing pourpose (not real data) once you get live access you shold use https://authservice.priaid.ch/login
priaid_healthservice_url = "https://sandbox-healthservice.priaid.ch" # Be aware that sandbox link is for testing pourpose (not real data) once you get live access you shold use https://healthservice.priaid.ch
language = "en-gb" # en-gb, de-ch, fr-fr, es-es, ru-ru, tr-tr, sk-sk...
pritnRawOutput = False # This flag can be set to see printed json data structure of webservice responses
age = '1994'

betterDoctorUID = {"cardiologist": "cardiologist",
"acupuncturist": "acupuncturist",
"allergist": "allergist",
"child psychiatry": "child-psychiatry",
"plastic surgeon": "plastic-surgeon",
"dermatologist": "dermatologist",
"endocrinologist": "endocrinologist",
"forensic psychologist": "forensic-psychologist",
"gastroenterologist": "gastroenterologist",
"general practitioner": "general-practitioner",
"geriatric medicine doctor": "geriatric-medicine-doctor",
"gynecologist": "gynecologist",
"internal medicine doctor": "internal-medicine-clinical-laboratory-immunology, internal-medicine-adolescent-medicine, internal-medicine-bariatric-medicine, internal-medicine-sports-medicine, internal-medicine-allergy-immunology, internal-medicine-magnetic-resonance-imaging-mri, internal-medicine-clinical-cardiac-electrophysiology, internal-medicine-hematology, internal-medicine-hypertension-specialist",
"plastic surgery surgery of the hand": "plastic-surgery-surgery-of-the-hand",
"hematopathologist": "hematopathologist",
"infectious disease doctor": "infectious-disease-doctor",
"rehabilitation chiropractor": "rehabilitation-chiropractor",
"oral maxillofacial surgeon": "oral-maxillofacial-surgeon",
"nephrologist": "nephrologist",
"neurologist": "neurologist",
"occupational therapist": "occupational-therapist",
"oncologist": "oncologist",
"ophthalmologist": "ophthalmologist",
"orthotist": "orthotist",
"otolaryngology facial plastic surgeon": "otolaryngology-facial-plastic-surgeon",
"pathologist": "pathologist",
"pediatrician": "pediatrician",
"pulmonologist": "pulmonologist",
"psychiatrist": "psychiatrist",
"sports medicine doctor": "sports-medicine-doctor",
"general surgeon": "general-surgeon",
"diagnostic radiologist": "diagnostic-radiologist",
"rheumatologist": "rheumatologist",
"urologist": "urologist",
"orthodontist": "orthodontist",
"oral surgeon": "oral-surgeon",
"periodontist" : "periodontist",
"general-practitioner" : "general-practitioner"}

specializationToSpecialist = {"Cardiology": "cardiologist",
"Acupuncture": "acupuncturist",
"Allergology": "allergist",
"Child psychiatry": "Child psychiatry",
"Plastic surgery": "plastic surgeon",
"Dermatology": "dermatologist",
"Endocrinology": "endocrinologist",
"Forensic medicine": "forensic psychologist",
"Gastroenterology": "gastroenterologist",
"General practice": "general practitioner",
"Geriatric medicine": "geriatric medicine doctor",
"Gynecology": "gynecologist",
"Internal medicine": "internal medicine doctor",
"Hand surgery": "plastic surgery surgery of the hand",
"Hematology": "hematopathologist",
"Infectiology": "infectious disease doctor",
"Manual medicine": "rehabilitation chiropractor",
"Maxillo Surgery": "oral maxillofacial surgeon",
"Nephrology": "nephrologist",
"Neurology": "neurologist",
"Occupational medicine": "occupational therapist",
"Oncology": "oncologist",
"Ophthalmology": "ophthalmologist",
"Orthopedics": "orthotist",
"Otolaryngology": "otolaryngology facial plastic surgeon",
"Pathology": "pathologist",
"Pediatrics": "pediatrician",
"Pulmonology": "pulmonologist",
"Psychiatry": "psychiatrist",
"Sports medicine": "sports medicine doctor",
"Surgery": "general surgeon",
"Radiology": "diagnostic radiologist",
"Rheumatology": "rheumatologist",
"Urology": "urologist",
"Orthodontics": "orthodontist",
"Oral surgery": "oral sur",
"general-practitioner": "general-practitioner"}
